### ISSUE TITLE
"Too many redirects" message error in axel command

### ISSUE THREAD

**Issue by redwolf1410** [aws-samples/amazon-sagemaker-spark-ui#2]
There is an error in the line 55 of the install-script [https://github.com/aws-samples/amazon-sagemaker-spark-ui/blob/v0.1.0/install-scripts/install-history-server.sh#L55](url). I am getting "Too many redirects" when I run this line from the terminal in sagemaker removing the -q option of the line to get the stdout. There are at least 2 issues in the axel repository where this problem is reported. [https://github.com/axel-download-accelerator/axel/issues/175](url), [https://github.com/axel-download-accelerator/axel/issues/339](url). Same line appears in the v0.2.0 in the studio-classic folder https://github.com/aws-samples/amazon-sagemaker-spark-ui/blob/v0.2.0/install-scripts/studio-classic/install-history-server.sh#L56. 
This started to happen just some days ago, like 1 week ago it worked. Please check it and let me know whatever could be useful. Thank you

**Comment by elmehdibelgasmi** [comment]
Getting the same error. For now I am using WGET instead in [install-history-server.sh](https://github.com/aws-samples/amazon-sagemaker-spark-ui/issues/url), although slower.

Current line (axel):
```
axel -q --output ./spark-$SPARK_VERSION-bin-without-hadoop.tgz --num-connection 10 https://archive.apache.org/dist/spark/spark-$SPARK_VERSION/spark-$SPARK_VERSION-bin-without-hadoop.tgz
```
Replaced by (wget):
```
wget -O ./spark-$SPARK_VERSION-bin-without-hadoop.tgz https://archive.apache.org/dist/spark/spark-$SPARK_VERSION/spark-$SPARK_VERSION-bin-without-hadoop.tgz
```

**Comment by brunopistone** [comment]
Hello @redwolf1410 , @elmehdibelgasmi . Thanks for sharing your feedback. We are going to review and update the solution. If you want to contribute, the repository it's open-source and you can follow the guidelines [CONTRIBUTING.md](https://github.com/aws-samples/amazon-sagemaker-spark-ui/blob/main/CONTRIBUTING.md), by opening a pull-request that will be reviewed by the team. Really thank you for sharing your feedbacks!

**Comment by brunopistone** [comment]
Thanks @elmehdibelgasmi for your contribution. install script for studio-classic tested and updated
